### ISSUE TITLE
GTK4: Cover picker

### ISSUE THREAD

**Issue by mizaki** [GeoRW/ACBF-Editor#10]
Currently missing a cover picker. My idea is to be able to click on the cover in the main window and bring up a dialog with thumbnails of all the pages to choose from.

**Comment by GeoRW** [comment]
Normally plain CBZ file has files inside named in such a way that coverpage come first when ordered, but might be a case if it's not.
The only thing is, if coverpage does not come first when filenames are ordered, it will not show properly in other viewers who cannot read ACBF.
So maybe Editor should also rename the file if needed?

**Comment by mizaki** [comment]
My thinking was all that needs to be changed is the `href` in `<image href="cover.jpg"/>` for example?

It maybe that a "rearrange" window is needed too and that could offer to rename files/rebuild the archive? Possibly could be done in the text layer window. (I do want to have the page list show as thumbnails as an option too in the text layer window.)
